spring:
  application:
    name: springboot-hello
  datasource:
    url: jdbc:mysql://localhost:33336/shopdevgo
    username: root
    password: root1234
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
#$ curl -X POST http://localhost:8080/user/add -H "Content-Type:  application/json" -d '{"userName": "two", "userEmail":"minhchi@gmail.com"}'
#  $ curl http://localhost:8080/user/search\?email\=minhchi@gmail.com\&name\=two